name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Node Modules
        run: npm ci
      - name: Run Tests
        run: npm run test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: test-coverage
          path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: |
          npm install -g surge
          npx surge --project ./build --domain tan-act.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
